version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-test
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8001:80"
